import Head from "next/head";
import Header from "./header";
import Footer from "./footer";


export default function Layout({ children } : any) {

    return(
        <>
            <div className="bg-white w-full h-full">
                <Head>
                    <title>연습장</title>
                    <meta name="description" content="Generated by create next app" lang="kor"/>
                    <link rel="icon" href="/public/favicon.ico" />
                </Head>
                <Header/>
                <div>{children }</div>
                <Footer/>
            </div>
        </>
    )
}