import Head from "next/head";
import Header from "./layout/header";
import Footer from "./layout/footer";


export default function Layout({children} : any ) {
    return(
        <>

            <Head>
                <title>Next App</title>
                <meta name="description" content="Generated by create next app" lang="kor"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <div>{children}</div>
            <Footer/>
        </>
    )
}