import Head from "next/head";
import Header from "./header";
import Footer from "./footer";


export default function Layout({children} : any ) {
    return(
        <>
            <div className="bg-white w-full h-full">
                <Head>
                    <title>Next App</title>
                    <meta name="description" content="Generated by create next app" lang="kor"/>
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header/>
                <div>{children}</div>
                <Footer/>
            </div>
        </>
    )
}